// Automatically generated by astro-icon
// a80adb6867c123891aa08bd370404717a0dd245efc3317683a863e06785cbef8

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "mdi:instagram"
		| "mdi:linkedin"
		| "mdi:whatsapp"
		| "mdi:email";
}