// Automatically generated by astro-icon
// 5aa430d371b33ad575b133a2ab096938eafeb08a34c04accbcaea195854d54f4

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "mdi:instagram"
		| "mdi:linkedin"
		| "mdi:whatsapp";
}