// Automatically generated by astro-icon
// b2615068b629535ede49deaf77faaff9a4f444df3eb005456718f695c343183e

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "mdi:instagram"
		| "mdi:linkedin"
		| "mdi:whatsapp"
		| "placeholder-logo";
}